steps:
  # Build Docker Image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t", "gcr.io/silver-antonym-324409/api-auth-service:$COMMIT_SHA",
        "-f", "api-auth-service/Dockerfile",
        "."
      ]

  # Push Docker Image lên Google Container Registry (GCR)
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/silver-antonym-324409/api-auth-service:$COMMIT_SHA"]

  # Deploy lên Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run", "deploy", "api-auth-service",
        "--image", "gcr.io/silver-antonym-324409/api-auth-service:$COMMIT_SHA",
        "--region", "asia-east1",
        "--platform", "managed",
        "--allow-unauthenticated",
        "--port", "4040"
      ]

# Define a Google Cloud Storage bucket for build logs
logsBucket: "gs://flms-service-log-fork"

images:
  - "gcr.io/silver-antonym-324409/api-auth-service:$COMMIT_SHA"

# Set build timeout to 15 minutes
timeout: 900s
